-- AlterTable
ALTER TABLE "auctions" ALTER COLUMN "open_at" SET DATA TYPE TIMESTAMPTZ(3),
ALTER COLUMN "close_at" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "race_entries" ALTER COLUMN "race_date" SET DATA TYPE TIMESTAMPTZ(3);

-- AlterTable
ALTER TABLE "races" ALTER COLUMN "date" SET DATA TYPE TIMESTAMPTZ(3);
