export const DIVISION = {
  SINGLE_OPEN_MEN: 'SINGLE_OPEN_MEN',
  SINGLE_OPEN_WOMEN: 'SINGLE_OPEN_WOMEN',
  SINGLE_PRO_MEN: 'SINGLE_PRO_MEN',
  SINGLE_PRO_WOMEN: 'SINGLE_PRO_WOMEN',
  DOUBLES_OPEN_MEN: 'DOUBLES_OPEN_MEN',
  DOUBLES_OPEN_WOMEN: 'DOUBLES_OPEN_WOMEN',
  DOUBLES_OPEN_MIXED: 'DOUBLES_OPEN_MIXED',
  DOUBLES_PRO_MEN: 'DOUBLES_PRO_MEN',
  DOUBLES_PRO_WOMEN: 'DOUBLES_PRO_WOMEN',
  RELAY_MEN: 'RELAY_MEN',
  RELAY_WOMEN: 'RELAY_WOMEN',
  RELAY_MIXED: 'RELAY_MIXED',
} as const;

export type RaceDivisionCode = (typeof DIVISION)[keyof typeof DIVISION];
